name: Run MATLAB Script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2

      - name: Set script name in MATLAB
        uses: matlab-actions/run-command@v2
        with:
          command: >
            file = 'docs/matlab/sandbox_script.m';
            [path, name, ext] = fileparts(file);
            dy_path = ['tmp/' path];
            dy_file = [dy_path name '.diary'];
            mkdir(dy_path);
            diary(dy_file);
            run(file);
            diary off;
      - name: Archive Diary
        uses: actions/upload-artifact@v4
        with:
          name: diary
          path: tmp/docs/matlab/sandbox_script.diary
